export const WeatherDictionary: { [key: number]: string } = {
    0: 'cloud_lock',
    1: 'sunny',
    101: 'bedtime',
    2: 'partly_cloudy_day',
    102: 'nights_stay',
    3: 'partly_cloudy_day',
    103: 'nights_stay',
    4: 'cloud',
    104: 'cloud',
    5: 'rainy',
    105: 'rainy',
    6: 'weather_snowy',
    106: 'weather_snowy',
    7: 'snowing',
    107: 'snowing',
    8: 'sunny_snowing',
    108: 'sunny_snowing',
    9: 'sunny_snowing',
    109: 'sunny_snowing',
    10: 'weather_mix',
    110: 'weather_mix',
    11: 'foggy',
    111: 'foggy',
    12: 'mist',
    112: 'mist',
    13: 'severe_cold',
    113: 'severe_cold',
    14: 'thunderstorm',
    114: 'thunderstorm',
    15: 'rainy_light',
    115: 'rainy_light',
    16: 'storm',
    116: 'storm',

};